image: trzeci/emscripten:sdk-tag-1.38.43-64bit

pages:
  only:
    refs:
      - master
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
  - bash ./build_html.sh
  artifacts:
    paths:
    - public